In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/data.csv', encoding='cp1252')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [3]:
df.shape

(541909, 8)

In [4]:
df['month'] = pd.to_datetime(df['InvoiceDate']).dt.month
df['total_price'] = df['Quantity'] * df['UnitPrice']

Which products are bought together?
Hypotheses:
1. Buying tea/coffee customer buy something sweet for good combination.

In [5]:
print("How many products are in data in the database?")
len(df['Description'].unique())

How many products are in data in the database?

4224

In [6]:
print("What is the largest amount of products in one order?")
int(df.groupby('InvoiceNo')['Description'].count().max())

What is the largest amount of products in one order?

1114

In [7]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,month,total_price
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,12,15.30
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,12,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,12,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,12,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,12,20.34

In [8]:
df.loc[df.duplicated(keep=False)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,month,total_price
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,12/1/2010 11:45,4.95,17908.0,United Kingdom,12,4.95
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,12/1/2010 11:45,2.10,17908.0,United Kingdom,12,2.10
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,12/1/2010 11:45,1.25,17908.0,United Kingdom,12,1.25
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,12/1/2010 11:45,1.25,17908.0,United Kingdom,12,1.25
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,12/1/2010 11:45,2.95,17908.0,United Kingdom,12,2.95
...,...,...,...,...,...,...,...,...,...,...
541675,581538,22068,BLACK PIRATE TREASURE CHEST,1,12/9/2011 11:34,0.39,14446.0,United Kingdom,12,0.39
541689,581538,23318,BOX OF 6 MINI VINTAGE CRACKERS,1,12/9/2011 11:34,2.49,14446.0,United Kingdom,12,2.49
541692,581538,22992,REVOLVER WOODEN RULER,1,12/9/2011 11:34,1.95,14446.0,United Kingdom,12,1.95
541699,581538,22694,WICKER STAR,1,12/9/2011 11:34,2.10,14446.0,United Kingdom,12,2.10
541701,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,12/9/2011 11:34,2.08,14446.0,United Kingdom,12,2.08

This is probably cause of adding the same product one by one without changing quantity so there is no need to drop duplicates.

In [9]:
# from itertools import permutations
# products_similarity = {product:{'total':0} for product in df['Description'].unique()}
#
# orders = df['InvoiceNo'].unique()
# for order in orders:
#     products = df['Description'].loc[df['InvoiceNo'] == order].unique()
#     permutation_products = permutations(products,2)
#     for products in permutation_products:
#         if products[1] in products_similarity[products[0]]:
#             products_similarity[products[0]][products[1]] += 1
#         else:
#             products_similarity[products[0]][products[1]] = 1
#         products_similarity[products[0]]['total'] += 1

In [10]:
# x = pd.DataFrame(products_similarity).T
# x.fillna(0, inplace=True)
# x.head()

In [11]:
# recommendations = x.drop(['total'], axis=1)
# recommendations = recommendations.div(x["total"], axis=0)
# recommendations.head()

In [12]:
# recommendations.to_csv('data/recommendations.csv',)

What product are similar to by name?

In [13]:
import torch
import spacy
nlp = spacy.load("en_core_web_lg")

In [ ]:
similar_by_name = pd.DataFrame(index=df['Description'].unique(), columns=df['Description'].unique())
for row in similar_by_name.index:
    row_token = nlp(row)
    for col in similar_by_name.columns:
        try:
            col_token = nlp(col)
            similar_by_name.loc[row, col]= row_token.similarity(col_token)
        except:
            similar_by_name.loc[row, col] = 0
            print(col)
            print(row)

nan

C:\Users\adamp\AppData\Local\Temp\ipykernel_51596\3633144410.py:7: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  similar_by_name.loc[row, col]= row_token.similarity(col_token)

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [ ]:
similar_by_name.to_csv('../data/similar_by_name.csv', index=False)